version: '3.8'

services:
  app:
    build: .
    container_name: whatsapp_app
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:15-alpine
    container_name: whatsapp_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sidharth@12
      - POSTGRES_DB=whatsapp_trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  pgdata:
